version: '3.9'

services:
  authdb:
    image: mongo:latest
    hostname: auth_mongo
    environment: 
      - MONGO_INITDB_DATABASE=authdb
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - 27017:27017
  auth:
    build: ./AuthService
    command: python -u app.py
    ports: 
      - "5001:5001"
    depends_on:
      - authdb
  web:
    build: ./WebService
    command: python app.py -debug
    ports:
      - "5002:5002"
  company:
    build: ./CompanyDataService
    command: ./app.py
    ports:
      - "5003:5003"
    depends_on:
      - companydb
  companydb:
    image: mongo:latest
    hostname: company_mongo
    environment: 
      - MONGO_INITDB_DATABASE=companydb
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - 27018:27018
    
